### PR TITLE
Update Login Signup

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Update the login and signup screens, which includes updating the minimum SDK version to 23, updating the target SDK version to 28, updating from the support library to Android X, and updating the tests.

### Test
Simperium does not have a stand-alone application so there is nothing to run directly on a device or emulator other than tests. The following commands can be run from the project's root directory while a device or emulator running API 23 is connected to mimic the continuous integration environment and ensure the tests pass.

```
./gradlew connectedCheck
./gradlew cAT
```

### Review
Only one developer is required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Review by AmandaRiu — COMMENTED** [review]
@theck13 

I ran `./gradlew connectedTest` and had the following tests fail. It looks like all of them are related to expecting json elements to be in a particular order. Maybe switch to checking individual elements? Here are the deets:

**ChangeTest.testModifyPayload**
```
junit.framework.ComparisonFailure: expected:<{"[tags":[],"deleted":false],"title":"Hola Mundo...> but was:<{"[deleted":false,"tags":[]],"title":"Hola Mundo...>
at com.simperium.android.PersistentStoreTest.testSavingObject(PersistentStoreTest.java:46)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:195)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:181)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:564)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
```

**ChannelTest.testInitMessageWithChangeVersion**
```
junit.framework.ComparisonFailure: expected:<init:{"[library":"android","cmd":"cv:fake-cv","token":"fake-token","version":0,"api":"1.1","name":"notes","app_id":"APP_ID","clientid":"SESSION-ID]"}> but was:<init:{"[clientid":"SESSION-ID","library":"android","name":"notes","api":"1.1","cmd":"cv:fake-cv","app_id":"APP_ID","version":0,"token":"fake-token]"}>
at com.simperium.ChannelTest.testInitMessageWithChangeVersion(ChannelTest.java:415)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:195)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:181)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:564)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
```

**ChannelTest.testInitMessageWithNoChangeVersion**
```
junit.framework.ComparisonFailure: expected:<init:{"[library":"android","cmd":"i::::50","token":"fake-token","version":0,"api":"1.1","name":"notes","app_id":"APP_ID","clientid":"SESSION-ID]"}> but was:<init:{"[clientid":"SESSION-ID","library":"android","name":"notes","api":"1.1","cmd":"i::::50","app_id":"APP_ID","version":0,"token":"fake-token]"}>
at com.simperium.ChannelTest.testInitMessageWithNoChangeVersion(ChannelTest.java:394)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:195)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:181)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:564)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
```

**PersistentStoreTest.testSavingObject**
```
junit.framework.ComparisonFailure: expected:<{"[tags":[],"deleted":false],"title":"Hola Mundo...> but was:<{"[deleted":false,"tags":[]],"title":"Hola Mundo...>
at com.simperium.android.PersistentStoreTest.testSavingObject(PersistentStoreTest.java:46)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:195)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:181)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:564)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
```

**Comment by theck13** [comment]
@AmandaRiu, which API version did you use?  I saw the tests fail when running on an emulator with API 28.  If I run on an emulator with API 23, the tests pass.  It seems like the JSON is ordered differently on different API versions for some reason.

We could probably change the tests to check for individual elements rather than comparing the entire object.  I tried to modify the tests as little as possible by updating the activity used only and not changing the functionality to ensure the behavior is the same as before.

**Comment by AmandaRiu** [comment]
@theck13 

> which API version did you use?

Yup, I used API 28. I really recommend changing the tests to check for individual elements so they can be run successfully on any device.

**Comment by theck13** [comment]
I updated the tests to ignore the data order in 8b324f7.  I verified they pass on API 23, 25, 26, and 28.

**Review by AmandaRiu — APPROVED** [review]
Ran the tests and reviewed the code. Nothing to really run so that's where I left it. LGTM! :shipit:

**Pull request merged**
