### PR TITLE
Implementing new socket API methods

### PR DESCRIPTION
**Pull request by beaucollins**
Adds [Server to Client](https://gist.github.com/beaucollins/6998802#server-to-client-commands) protocol methods:
- Reverse index interrogation method (simperium sends an `index`) to the client
- Connection level `log` message

Also adding unit tests to ensure the client adheres to [the protocol](https://gist.github.com/beaucollins/6998802).

### CODE REVIEW

**Comment by chengfred** [comment]
Saw the `cv:?` `c:?` references so thought maybe here is good place:

Simperium/poutine/issues/74

New clients should send a "library" and a "version" > 0 in init to get the `cv:?` response

**Comment by beaucollins** [comment]
@fredrocious does "pending" mean changes that our client considers to have sent but has not received an acknowledged change yet?

**Comment by chengfred** [comment]
Yeah - feel free to add in more state info beyond what is listed, intent is
just to help us figure out what is going on in the client. I doubt we will
be parsing this to display server-side, at least not initially. I guess an
automated side-by-side compare would be cool though.

**Comment by beaucollins** [comment]
retest this please

**Pull request merged**
